bookings_db = {
    '1': {
        "booking_id": "1",
        "user_id": "1",
        "start_date": "2024-08-01",
        "end_date": "2024-08-05",
        "is_cancelled": False,
        "is_paid": True,
        "price": 1000.35,
        "room_type": "DELUXE",
    },
    "2": {
        "booking_id": "2",
        "user_id": "15",
        "start_date": "2024-04-01",
        "end_date": "2024-04-03",
        "is_cancelled": False,
        "is_paid": True,
        "price": 474.73,
        "room_type": "SINGLE",
    },
    "3": {
        "booking_id": "3",
        "user_id": "4",
        "start_date": "2024-09-01",
        "end_date": "2024-09-05",
        "is_cancelled": True,
        "is_paid": True,
        "price": 2354.24,
        "room_type": "SUITE",
    },
}